Repository MetaMask/accounts, pull requests merged in 2024-10, with the labels that each got.

#76 chore(keyring-api): update peer dependency `@metamask/providers@^17.2.0` -> `^18.1.0`
  packages/keyring-api/package.json
  yarn.lock
Labels: team-accounts, team-hardware-wallets

#79 chore: bump dependency `eth-sig-util@^7.0.3` -> `^8.0.0`
  packages/keyring-eth-hd/package.json
  packages/keyring-eth-ledger-bridge/package.json
  packages/keyring-eth-simple/package.json
  packages/keyring-eth-trezor/package.json
  packages/keyring-snap-bridge/package.json
  yarn.lock
Labels: team-accounts

#81 chore(deps): bump `secp256k1` to 4.0.4
  yarn.lock
Labels: security, dependency
